# Generated by Django 6.0.3 on 2026-03-04 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=225)),
                ('descripcion', models.CharField(max_length=225)),
                ('precio', models.CharField(max_length=225)),
                ('imagen', models.CharField(max_length=225)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=225)),
                ('descripcion', models.CharField(max_length=225)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
                ('id_permiso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=225)),
                ('descripcion', models.CharField(max_length=225)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creart.roles')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Solicitudes',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('detalles', models.CharField(max_length=225)),
                ('cantidad', models.CharField(max_length=225)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creart.productos')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('id_transaccion', models.IntegerField(unique=True)),
                ('hora', models.TimeField()),
                ('importe_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moneda', models.CharField(max_length=225)),
                ('comisiones', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(max_length=225)),
                ('token', models.CharField(max_length=225)),
                ('ip_cliente', models.CharField(max_length=225)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creart.solicitudes')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=225)),
                ('documento', models.CharField(max_length=225)),
                ('apellido', models.CharField(max_length=225)),
                ('correo', models.CharField(max_length=225)),
                ('numero', models.CharField(max_length=225)),
                ('contrasena', models.CharField(max_length=225)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creart.roles')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creart.usuarios'),
        ),
        migrations.AddField(
            model_name='productos',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creart.usuarios'),
        ),
        migrations.CreateModel(
            name='PQRS',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
                ('id_pqrs', models.AutoField(primary_key=True, serialize=False)),
                ('causa_problema', models.CharField(max_length=225)),
                ('mensaje', models.CharField(max_length=225)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creart.usuarios')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
