# Generated by Django 5.0 on 2026-03-18 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creart', '0002_alter_usuarios_contrasena'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='estado_aprobacion',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado')], default='pendiente', max_length=20),
        ),
    ]
