# Generated by Django 6.0.3 on 2026-03-20 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creart', '0003_productos_estado_aprobacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pqrs',
            old_name='causa_problema',
            new_name='asunto',
        ),
        migrations.AddField(
            model_name='pqrs',
            name='categoria',
            field=models.CharField(choices=[('pregunta', 'Pregunta'), ('queja', 'Queja'), ('reporte', 'Reporte'), ('solicitud', 'Solicitud')], default='pregunta', max_length=20),
        ),
        migrations.AddField(
            model_name='pqrs',
            name='estado_respuesta',
            field=models.CharField(choices=[('sin_respuesta', 'Sin_respuesta'), ('respondido', 'Respondido')], default='sin_respuesta', max_length=20),
        ),
    ]
