# Generated by Django 6.0.3 on 2026-03-20 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creart', '0004_rename_causa_problema_pqrs_asunto_pqrs_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='categoria',
            field=models.CharField(choices=[('antojos', 'Antojos'), ('eventos', 'Eventos')], default='antojos', max_length=20),
        ),
    ]
