# Generated by Django 6.0.3 on 2026-03-20 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creart', '0006_alter_productos_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pqrs',
            name='mensaje',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='SolicitudPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(blank=True, max_length=225, null=True)),
                ('apellido', models.CharField(blank=True, max_length=225, null=True)),
                ('correo', models.CharField(blank=True, max_length=225, null=True)),
                ('numero', models.CharField(blank=True, max_length=225, null=True)),
                ('direccion', models.CharField(blank=True, max_length=225, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creart.usuarios')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
