# Generated by Django 6.0.3 on 2026-03-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creart', '0007_alter_pqrs_mensaje_solicitudperfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='direccion',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
