# Generated by Django 6.0.3 on 2026-03-24 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creart', '0008_usuarios_direccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='solicitud',
        ),
        migrations.RemoveField(
            model_name='solicitudes',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='solicitudes',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='solicitudes',
            name='detalles',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='documento',
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='abono',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='cobertura',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='decoracion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='direccion_entrega',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='fecha_evento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='mensaje_pastel',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='mp_payment_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='mp_preference_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='nombre_invitado',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='pisos',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='porciones',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='rellenos',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='tipo_entrega',
            field=models.CharField(default='tienda', max_length=20),
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creart.usuarios'),
        ),
        migrations.AlterField(
            model_name='permisos',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='permisos',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='productos',
            name='categoria',
            field=models.CharField(choices=[('antojos', 'Antojos'), ('eventos', 'Eventos')], default='diarios', max_length=20),
        ),
        migrations.AlterField(
            model_name='productos',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='productos',
            name='estado_aprobacion',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('diarios', 'Diarios')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(upload_to='productos/'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='roles',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='roles',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('pagada', 'Pagada')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='apellido',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='contrasena',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='correo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='numero',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='Transacciones',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_transaccion', models.AutoField(primary_key=True, serialize=False)),
                ('hora', models.TimeField()),
                ('importe_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moneda', models.CharField(max_length=225)),
                ('comisiones', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(blank=True, max_length=225)),
                ('token', models.CharField(max_length=225)),
                ('ip_cliente', models.CharField(max_length=225)),
                ('mp_payment_id', models.CharField(blank=True, max_length=200)),
                ('estado', models.CharField(choices=[('abonado', 'Abonado'), ('terminado', 'Terminado')], default='abonado', max_length=20)),
                ('solicitud', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='creart.solicitudes')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='SolicitudPerfil',
        ),
        migrations.DeleteModel(
            name='Transaccion',
        ),
    ]
