# Generated by Django 6.0.3 on 2026-03-27 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creart', '0009_remove_transaccion_solicitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='motivo_rechazo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='categoria',
            field=models.CharField(choices=[('antojos', 'Antojos'), ('eventos', 'Eventos'), ('diarios', 'Diarios')], default='diarios', max_length=20),
        ),
        migrations.AlterField(
            model_name='productos',
            name='estado_aprobacion',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
    ]
