# Generated by Django 6.0.3 on 2026-03-27 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creart', '0010_productos_motivo_rechazo_alter_productos_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacciones',
            name='estado_tran',
            field=models.CharField(choices=[('abonado', 'Abonado'), ('terminado', 'Terminado')], default='abonado', max_length=20),
        ),
        migrations.AlterField(
            model_name='transacciones',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
