# Generated by Django 6.0.3 on 2026-03-27 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creart', '0011_transacciones_estado_tran_alter_transacciones_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transacciones',
            name='estado_tran',
        ),
        migrations.RemoveField(
            model_name='transacciones',
            name='fecha_creacion',
        ),
        migrations.AlterField(
            model_name='transacciones',
            name='estado',
            field=models.CharField(choices=[('abonado', 'Abonado'), ('terminado', 'Terminado')], default='abonado', max_length=20),
        ),
    ]
