# Generated by Django 6.0.3 on 2026-03-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creart', '0012_remove_transacciones_estado_tran_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacciones',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
