# Generated by Django 6.0.3 on 2026-03-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creart', '0013_transacciones_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pqrs',
            name='respuesta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
