# Generated by Django 6.0.3 on 2026-03-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creart', '0014_pqrs_respuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudes',
            name='estado_habil',
            field=models.BooleanField(default=True),
        ),
    ]
