# Generated by Django 6.0.3 on 2026-04-07 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creart', '0015_solicitudes_estado_habil'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudes',
            name='correo_invitado',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
