# Generated by Django 6.0.3 on 2026-04-07 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creart', '0016_solicitudes_correo_invitado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
