# Generated by Django 6.0.4 on 2026-04-14 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creart', '0017_alter_productos_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudes',
            name='estado_habil',
        ),
    ]
