# Generated by Django 6.0.4 on 2026-04-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creart', '0018_remove_solicitudes_estado_habil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='contrasena',
            field=models.CharField(max_length=255),
        ),
    ]
