# Generated by Django 4.2.30 on 2026-04-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creart', '0020_inventario_proveedores_movimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='categoria',
            field=models.CharField(choices=[('harinas', 'Harinas'), ('lacteos', 'Lacteos'), ('endulzantes', 'Endulzantes'), ('licores', 'Licores'), ('frutas', 'Frutas'), ('chocolates', 'Chocolates'), ('aceites', 'Aceites'), ('huevos', 'Huevos'), ('manies', 'Manies'), ('frutos_rojos', 'Frutos_rojos')], default='Harinas', max_length=255),
        ),
        migrations.AddField(
            model_name='inventario',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='proveedores',
            name='empresa',
            field=models.CharField(default='', max_length=100),
        ),
    ]
