# Generated by Django 4.2.30 on 2026-04-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creart', '0021_inventario_categoria_inventario_precio_unitario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='unidad',
            field=models.CharField(choices=[('g', 'G'), ('kg', 'Kg'), ('ml', 'ML'), ('cc', 'CC'), ('l', 'L'), ('lb', 'Lb')], default='G', max_length=50),
        ),
    ]
