# Generated by Django 4.2.30 on 2026-05-06 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creart', '0022_alter_inventario_unidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedores',
            old_name='id_proveedores',
            new_name='id_proveedor',
        ),
    ]
