# Generated by Django 4.2.30 on 2026-05-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creart', '0023_rename_id_proveedores_proveedores_id_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='categoria',
            field=models.CharField(choices=[('harinas', 'Harinas'), ('lacteos', 'Lacteos'), ('endulzantes', 'Endulzantes'), ('licores', 'Licores'), ('frutas', 'Frutas'), ('chocolates', 'Chocolates'), ('aceites', 'Aceites'), ('huevos', 'Huevos'), ('manies', 'Manies'), ('frutos_rojos', 'Frutos_rojos')], default='Harinas', max_length=25),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='numero',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='transacciones',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
