# Generated by Django 4.2.30 on 2026-05-13 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creart', '0024_alter_inventario_categoria_alter_proveedores_numero_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecetaProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
                ('cantidad_por_porcion', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creart.inventario')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receta', to='creart.productos')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
