# Generated by Django 5.0 on 2026-06-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creart', '0025_recetaproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='token_activacion',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='categoria',
            field=models.CharField(choices=[('harinas', 'Harinas'), ('lacteos', 'Lacteos'), ('endulzantes', 'Endulzantes'), ('licores', 'Licores'), ('frutas', 'Frutas'), ('chocolates', 'Chocolates'), ('aceites', 'Aceites'), ('huevos', 'Huevos'), ('manies', 'Manies'), ('frutos_rojos', 'Frutos_rojos')], default='harinas', max_length=25),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='unidad',
            field=models.CharField(choices=[('g', 'G'), ('kg', 'Kg'), ('ml', 'ML'), ('cc', 'CC'), ('l', 'L'), ('lb', 'Lb')], default='g', max_length=50),
        ),
    ]
