"""
Django settings for creart1 project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-x5j86f^p0^xdqkddoq!b*0q7(c-ckqzcs(6dl3i^bg#*hul825'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'creart',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'creart1.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'creart1.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
# ===================== MERCADOPAGO =====================
# Cuando tengas tu cuenta, reemplaza estos valores y descomenta:
# MERCADOPAGO_ACCESS_TOKEN = 'TEST-xxxxxxxxxxxxxxxxxxxx'
# MERCADOPAGO_PUBLIC_KEY = 'TEST-xxxxxxxxxxxxxxxxxxxx'

# Por ahora usamos modo simulado
MERCADOPAGO_ACCESS_TOKEN = 'APP_USR-7756347471270828-031815-63ad9159bc545ef0ed6cd8c620ef4ddf-3275706265'
MERCADOPAGO_PUBLIC_KEY = 'APP_USR-383f7c20-62de-4242-b3ee-af214f709acb'
MERCADOPAGO_SIMULADO = True  # cambiar a False cuando tengas credenciales
# =======================================================

# ===================== MERCADOPAGO =====================
MERCADOPAGO_ACCESS_TOKEN = 'APP_USR-7756347471270828-031815-63ad9159bc545ef0ed6cd8c620ef4ddf-3275706265'
MERCADOPAGO_PUBLIC_KEY = 'APP_USR-383f7c20-62de-4242-b3ee-af214f709acb'
MERCADOPAGO_SIMULADO = False  
# =======================================================
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'