# Generated by Django 3.2.25 on 2026-03-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creart2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='categoria',
            field=models.CharField(choices=[('antojos', 'Antojos'), ('eventos', 'Eventos'), ('diarios', 'Diarios')], default='diarios', max_length=20),
        ),
    ]
