# Generated by Django 3.2.25 on 2026-03-18 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creart2', '0002_productos_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='comisiones',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='hora',
        ),
        migrations.AddField(
            model_name='transaccion',
            name='solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creart2.solicitud'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='token_tarjeta',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
