# Generated by Django 3.2.25 on 2026-03-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creart2', '0003_auto_20260318_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='ip_cliente',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='token_tarjeta',
        ),
        migrations.AddField(
            model_name='transaccion',
            name='mp_payment_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='estado',
            field=models.CharField(choices=[('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('pendiente', 'Pendiente')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='metodo_pago',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='moneda',
            field=models.CharField(default='COP', max_length=10),
        ),
    ]
