# Generated by Django 3.2.25 on 2026-03-18 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creart2', '0004_auto_20260318_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='fecha_solicitud',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='abono',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='cobertura',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='decoracion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='direccion_entrega',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('pagada', 'Pagada')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='fecha_evento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='mensaje_pastel',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='mp_payment_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='mp_preference_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='nombre_invitado',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='pisos',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='porciones',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='rellenos',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='tipo_entrega',
            field=models.CharField(default='tienda', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creart2.usuarios'),
        ),
    ]
