# Generated by Django 6.0.3 on 2026-03-04 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('detalles', models.TextField()),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id_permiso', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creart2.roles')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.ImageField(upload_to='productos/')),
                ('Solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creart2.solicitud')),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id_transaccion', models.AutoField(primary_key=True, serialize=False)),
                ('id_pedido', models.CharField(max_length=20, unique=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('importe_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moneda', models.CharField(max_length=10)),
                ('comision', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('token_tarjeta', models.CharField(max_length=100)),
                ('IP_cliente', models.GenericIPAddressField()),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creart2.solicitud')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('documento', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('numero', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=200)),
                ('contrasena', models.CharField(max_length=128)),
                ('Roles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creart2.roles')),
            ],
        ),
        migrations.AddField(
            model_name='solicitud',
            name='Usuarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creart2.usuarios'),
        ),
        migrations.CreateModel(
            name='PQRS',
            fields=[
                ('id_pqrs', models.AutoField(primary_key=True, serialize=False)),
                ('causa_problema', models.TextField()),
                ('mensaje', models.TextField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creart2.usuarios')),
            ],
        ),
    ]
